---
title: "Social Mobility - Final Report"
author: "Perach Hen Elkayam"
date: '2022-06-07'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

One character of a functioning society is not just the total wealth, but the social mobility in the society. A lack of social mobility might cause false consciousness of what is called a "Glass Ceiling" - a so called invisible barrier that prevents a given demographic from rising beyond a certain level in a hierarchy. Invisible or visible barriers might cause different subgroups of the population feel frustrated and may prevent them from making a progress or working hard for their future and for their families future.

In order to suggest a possible solution I analyzed the data from a 2018 survey by the Central Bureau of Statistics. First I built different prediction models in order to see if I can predict high socioeconomic status in the future (age 45- 54) based on the past (age 30). Afterwards I tried to find special groups based only on socioeconomic variables on the present. Last I tried to explore the distributions of the socioeconomic scores among different subgroups in order to add some inference and possible insights to my analysis. 

I found out that I can predict pretty well future socioeconomic status based on variables from the past, and that the most powerful predictor was having a military / national service. Using unsupervised learning I found 3 main subgroups based on the socioeconomic variables: Those who have high socioeconomic status in all aspects, those who tend to have no formal high education and a low income but claim to be satisfied with their lives and those  who are not satisfied with their lives but economically and in terms of education are somewhere between the other two clusters.



# Introduction

This project deals with the issue of social mobility in Israel. Social mobility is the movement of individuals, families, households, or other categories of people within or between social strata in a society. It is a change in social status relative to one's current social location within a given society. Because of the structure of the population in Israel that includes a big variety of cultures, I believe that it is easier to isolate variables that might indicate a possible improvement of socioeconomic status.

I find this issue very interesting because I can understand what is needed from someone in order to improve and change his social status. In this project I would like to find answers to the following questions:

-   Can we predict future social status by the background of the participant and his parents?
-   Can we characterize similar groups by features of socioeconomic status?
-   Can we identify variables that influence social mobility?

During the whole project I used a socioeconomic score that I created by myself as described in the following section.







# Data Description

The data set was collected by the Central Bureau of Statistics.

Through the analysis in order to isolate age as a possible confounder I decided to focus on a specific age group: 45 - 54.
This age group contains adults that probably made most of their big decisions and progress in their life.
Given a reasonable amount of useful data i stayed with 1098 observations.

X--------------y
(vars)         (vars)
(past)
(age 30) ----   (present age 45-54)


## Prediction Model:

### Creating the Predictors (X):

I chose 17 questions from the 409 available in the data that I assumed to be known at the age of 30.
I couldn't use most of the questions asked in the survey since the answers contained information about the future and therefore cannot be used as predictors.
For easier interpretation and modelling I preprocessed the original questions and created 11 new variables:


* `Minn` (Gender): Male or Female


* `birth_plcae` (Birth Place) - participant and parents birth place: USSR, Israel (parents: Mixed), Israel (parents: Israel), Israel (parents: Europe / America), Israel (parents: Asia), Israel (parents: Africa), Europe / America, Asia, Africa.


* `GilMegurimAtzmaim` - The age at which the participant moved to independent residence: haven't moved to independent residence, until age 17, 18-19, 20-21, 22-23, 24-25, 26-27, 28-29.


* `GilNisuinRishon` - First age of marriage: younger then 20, 20-21, 22-23, 24-25, 26-27, 28-29 and participants who didn't got married until age 30 .


* `GilYeledRishon` - Age at which the first child was born: until 19, 20-21, 22-23, 24-25, 26-27, 28-29, No children.


* `Ethnicity`: Jew-Secular, Jew-Masorti not very Religious, Jew-Masorti, Jew-Religious, Jew-Haredi, Musilm and Else group: Christians, Druze, other religions and atheists (collected into one group "Else" because they all had small number of participants).


* `TeudaGvohaEm_C` - Mother education: no education or non of the mentioned certificates, high school (without Bagrut certificate),
high school (with Bagrut certificate), Post-secondary school (not academic certificate), BA, MA, Ph.D.


* `TeudaGvohaAv_C` - Father education (same options as mother education) 


* `service` - Military or national service: yes or no.


* `mother_work_at_age_15` - The participant's mother employee status when the participant was 15 years old: Didn't work, Employee, Business owner, Else, Passed away.


* `father_work_at_age_15` - The participant's father employee status when the participant was 15 years old: (the same as mother).


### Creating the Socioeconomic score (Y):

There are many ways to measure and define socioeconomic status. I built a score for the socioeconomic status that is a combination of education, life quality, employment and economic status by using the variables that were available in the data:

- `TzfifutDiyurM` - How crowded is the living place: low (less than one in one room), middle or High (2+ in one room).

- `Mechonitbaalut_C` - How many cars does the participant have: 0, 1, 2, 3, 4, 5+.

- `MerutzeEzor` - How much does the participant is satisfied with his living area? 1-4.

- `MatzavBriut` - How much does the participant values is health condition generally? 1-4.

- `MatzavBriut` - How much does the participant values is health condition generally? 1-4.

- `TeudaGvoha` - Participant's education: The same levels as mentioned in the Mother Education variable.

- `PehamimShimushInt` - Frequency of internet use per week: Not at all, less than once a week, once or twice a week, everyday or almost everyday.

- `MerutzeKesherMishp` - How much are you satisfied with your family relationship? 1-5.

- `MerutzeKesherMishp` - How much are you satisfied with your family relationship? 1-5.

- `TadirutChaverim` - Frequency of interacting with friends: Not at all, less than once in a month, once or twice in a month, once or twice in a week, everyday or almost every day.

- `MerutzeChaim` - How much are you satisfied with your life? 1-4.

- `MerutzeKalkali` - How much are you satisfied with your economic status? 1-4.

- `HachnasaAvodaNeto` - Last week what was your income (Neto) from all of your workplaces? 0-2000, 2001-3000, 3001-4000, 4001-5000, 5001-6000, 6001-7500, 7501-10000, 10001-14000, 14001, 21000, above 21000.

- `Mispar_dirot` - How many apartments do you own? 0, 1, 2+.

I took all of the mentioned variables, scaled them and calculated the mean for each individual in the data set. 
Some of the variables indicate high socieconomic status in the opposite direction, for example: If your living place is less crowded your socioeconomic status is higher. In order to have consistency I multiplied these variables by -1 (the raw values are not important because of the scaling process).

In order to use the new variable for the prediction models it was easier for me to make it binary and produce probabilities for being in a high socioeconomic status. Calculated as a continuous value, and standardized: the mean value of the score will be zero, positive value means that the social economic status is above average.

I divided the data to training (821 observations) and test set (277 observations) randomly.

For more exploration I also used the `ShinuyRamatHaim` variable (Worse, Unchanged, Better or unknown) which stands for whether the participant's life got better in the last 10 years.

# Methods

# Limitations

I didn't had the data from the past \*\*\*

# Results, discussion and conclusion

I found that completing a military or national service is a great predictor for being in a high socioeconomic status in the future.

I assume that a possible reason is that taking a part in a military or a national service might make individuals feel as being an integral part of the society. Military or national service might make people having relationships more easily because of common experience or more satisfied by feeling like "giving their part" to society.

I suspect that this variable might be dominant because of the correlation with Jewish ethnicity, but it seems that there is a big difference in socieconomic status even among Jews who did and did not participate in a military or national service.

If my assumptions are correct, I think that the best way to deal with social mobility is to help all populations feel as part of the society by finding the right platforms.

# References

[Questionnaire and more details on the survey in The Central Bureau of Statistics website](https://www.cbs.gov.il/he/publications/Pages/2020/%D7%94%D7%A1%D7%A7%D7%A8-%D7%94%D7%97%D7%91%D7%A8%D7%AA%D7%99-2018.aspx)

